<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);MVVMTK0045</NoWarn>
    <UseWinUI>true</UseWinUI>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>Kontrol</AssemblyTitle>
    <Product>Kontrol</Product>
    <Copyright>2026 Mert Umut</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RootNamespace>Kontrol</RootNamespace>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\app.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" PrivateAssets="all" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250228001" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kontrol.Fan\Kontrol.Fan.csproj" />
    <ProjectReference Include="..\Kontrol.Rgb\Kontrol.Rgb.csproj" />
  </ItemGroup>

</Project>
